name = "elixir-chess-api"
main = "src/index.js"
compatibility_date = "2026-05-13"

[[routes]]
pattern = "api.elixirchess.karthikkashyap.com"
custom_domain = true

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Matchmaker"]
